SolvekEPayment/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SolvekEPayment.Banks;
using SolvekEPayment.Banks.Akbank;
using SolvekEPayment.Banks.Halkbank;
using SolvekEPayment.Banks.Isbank;
using SolvekEPayment.Banks.Teb;
using SolvekEPayment.Banks.Vakifbank;
using SolvekEPayment.Dtos.AppDtos;
using SolvekEPayment.Dtos.ErpDtos;
using SolvekEPayment.Helpers;
using SolvekEPayment.Models;
using SolvekEPayment.Services.AppServices.PaymentServices;
using SolvekEPayment.Services.ErpServices.CustomerServices;
using SolvekEPayment.SolvekLog;

namespace SolvekEPayment.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ICustomerService CustomerService;
        private readonly IHostingEnvironment HostingEnvironment;
        private readonly IPaymentInitControl PaymentInitControl;
        private readonly IPaymentRequest PaymentRequest;
        private readonly IPaymentStart PaymentStart, PaymentStartHalkbank, PaymentStartTeb, PaymentStartIsbank, PaymentStartVakifbank;
        private readonly ILog Log;
        private readonly IPaymentService PaymentService;
        private string vakifTerminalNo = "VP294104";
        private string vakifTransactionType = "Sale";
        public HomeController(ICustomerService customerService, IHostingEnvironment hostingEnvironment, IPaymentRequest paymentRequest,
            IPaymentInitControl paymentInitControl, PaymentStart paymentStart, HalkbankPaymentStart paymentStartHalkbank,
            IsbankPaymentStart paymentStartIsbank, VakifbankPaymentStart paymentStartVakifbank,
            TebPaymentStart paymentStartTeb, ILog log, IPaymentService paymentService)
        {
            CustomerService = customerService;
            PaymentRequest = paymentRequest;
            HostingEnvironment = hostingEnvironment;
            PaymentInitControl = paymentInitControl;
            PaymentStart = paymentStart;
            PaymentStartHalkbank = paymentStartHalkbank;
            PaymentStartTeb = paymentStartTeb;
            PaymentStartIsbank = paymentStartIsbank;
            PaymentStartVakifbank = paymentStartVakifbank;
            Log = log;
            PaymentService = paymentService;
        }

        public IActionResult Index()
        {
            TempData["result"] = false;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(PaymentStartDto paymentStartDto)
        {
            if (!ModelState.IsValid)
                return View();

            paymentStartDto.userId = Convert.ToInt32(Request.Cookies["userId"]);
            paymentStartDto.paymentType = PaymentTypeHelper.BALANCE;
            paymentStartDto.path = HostingEnvironment.WebRootPath;
            var controlModel = PaymentInitControl.control(paymentStartDto);
            MessageModelResponse result = null;
            if (controlModel.result)
            {
                paymentStartDto.pan = paymentStartDto.pan.Trim().Replace(" ", "");
                paymentStartDto.documentNumber = "";

                switch (paymentStartDto.bankId)
                {
                    case BankIdHelper.AKBANK:
                        result = PaymentStart.paymentStart(paymentStartDto);
                        break;
                    case BankIdHelper.HALKBANK:
                        result = PaymentStartHalkbank.paymentStart(paymentStartDto);
                        break;
                    case BankIdHelper.TEB:
                        result = PaymentStartTeb.paymentStart(paymentStartDto);
                        break;
                    case BankIdHelper.ISBANK:
                        result = PaymentStartIsbank.paymentStart(paymentStartDto);
                        break;
                    case BankIdHelper.VAKIFBANK:
                        result = PaymentStartVakifbank.paymentStart(paymentStartDto);
                        break;
                    default:
                        break;
                }

                if (result.result)
                {
                    TempData["result"] = false;
                    //Log.log($"{paymentStartDto.path}\\logbank\\{DateTime.Now.ToString("yyyy_MM_dd_HHmmssFFF")}_{paymentStartDto.userId}.xml", result.message);
                    byte[] bytes = Encoding.ASCII.GetBytes(result.message);
                    HttpContext.Response.Body.Write(bytes);
                }
                else
                {
                    TempData["result"] = true;
                    TempData["message"] = result.message;
                }
            }
            else
            {
                TempData["result"] = true;
                TempData["message"] = controlModel.message;
            }
            return View();
        }

        [AllowAnonymous]
        public IActionResult OkUrl([FromQuery]string bType)
        {
            var types = bType.Split('_');
            if (types[0] == "other")
            {
                List<KeyValuePair<String, String>> postParams = new List<KeyValuePair<String, String>>();
                foreach (string key in Request.Form.Keys)
                {
                    KeyValuePair<String, String> newKeyValuePair = new KeyValuePair<String, String>(key, Request.Form[key]);
                    postParams.Add(newKeyValuePair);
                }

                String hashVal = "";
                String paramskeys = "";

                postParams.Sort(
                delegate (KeyValuePair<string, string> firstPair,
                KeyValuePair<string, string> nextPair)
                {
                    return firstPair.Key.ToLower(new System.Globalization.CultureInfo("en-US", false)).CompareTo(nextPair.Key.ToLower(new System.Globalization.CultureInfo("en-US", false)));
                }
                );

                foreach (KeyValuePair<String, String> pair in postParams)
                {
                    String escapedValue = pair.Value.Replace("\\", "\\\\").Replace("|", "\\|");
                    String lowerValue = pair.Key.ToLower(new System.Globalization.CultureInfo("en-US", false));
                    if (!"encoding".Equals(lowerValue) && !"hash".Equals(lowerValue) && !"countdown".Equals(lowerValue))
                    {

                        hashVal += escapedValue + "|";
                        paramskeys += lowerValue + "|";
                    }
                }
                hashVal += AkbankHelper.storeKey;

                System.Security.Cryptography.SHA512 sha = new System.Security.Cryptography.SHA512CryptoServiceProvider();
                byte[] hashbytes = System.Text.Encoding.GetEncoding("UTF-8").GetBytes(hashVal);
                byte[] inputbytes = sha.ComputeHash(hashbytes);
                String actualHash = System.Convert.ToBase64String(inputbytes);

                string HASH = Request.Form["HASH"];

                string mdstatus = Request.Form["mdStatus"];
                //string hashparams = Request.Form["HASHPARAMS"];
                //string hashparamsval = Request.Form["HASHPARAMSVAL"];

                /*string paramsval = "";
                int index1 = 0, index2 = 0;

                if (hashparams != null)
                {
                    do
                    {
                        index2 = hashparams.IndexOf(":", index1);
                        string val1 = Request.Form[hashparams.Substring(index1, index2 - index1)];
                        string val = val1 == null ? "" : val1;
                        paramsval += val;
                        index1 = index2 + 1;
                    }
                    while (index1 < hashparams.Length);

                    string hashval = paramsval + AkbankHelper.storeKey;              //Store key is being added to hash value
                    string hashparam = Request.Form["HASH"];

                    System.Security.Cryptography.SHA1 sha = new System.Security.Cryptography.SHA1CryptoServiceProvider();
                    byte[] hashbytes = System.Text.Encoding.GetEncoding("ISO-8859-9").GetBytes(hashval);
                    byte[] inputbytes = sha.ComputeHash(hashbytes);

                    string hash = Convert.ToBase64String(inputbytes);   //Hash value used for validation*/

                    if (!actualHash.Equals(HASH)) //hash generated in this page, hash returned and hash generated from parsed parameters should be same
                    {
                        try
                        {
                            TempData["messageModel"] = JsonConvert.SerializeObject(new PaymentDto
                            {
                                message = MessageHelper.PAYMENT_HASH_ERROR,
                                oid = Request.Form["oid"],
                                userId = Convert.ToInt32(Request.Form["firmaadi"]),
                                transId = Request.Form["TransId"],
                                amount = Request.Form["amount"],
                                paymentType = PaymentTypeHelper.BALANCE
                            });
                        }
                        catch (Exception ex)
                        {

                        }
                        return RedirectToAction("PaymentFail", "Home");
                    }
                /*}
                else
                {
                    try
                    {
                        TempData["messageModel"] = JsonConvert.SerializeObject(new PaymentDto
                        {
                            message = MessageHelper.PAYMENT_HASH_EMPTY_ERROR,
                            oid = Request.Form["oid"],
                            userId = Convert.ToInt32(Request.Form["firmaadi"]),

SolvekEPayment/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using SolvekEPayment.Banks;
using SolvekEPayment.Banks.Akbank;
using SolvekEPayment.Dtos.AppDtos;
using SolvekEPayment.Dtos.ErpDtos;
using SolvekEPayment.Helpers;
using SolvekEPayment.Services.ErpServices.CustomerServices;

namespace SolvekEPayment.Controllers
{
    [Authorize]
    public class PaymentController : Controller
    {
        private readonly ICustomerService CustomerService;
        private readonly IPaymentStart PaymentStart;
        private readonly IHostingEnvironment HostingEnvironment;
        private readonly IPaymentInitControl PaymentInitControl;
        public PaymentController(ICustomerService customerService, IPaymentStart paymentStart,
            IHostingEnvironment hostingEnvironment, IPaymentInitControl paymentInitControl)
        {
            CustomerService = customerService;
            PaymentStart = paymentStart;
            HostingEnvironment = hostingEnvironment;
            PaymentInitControl = paymentInitControl;
        }

        /*public IActionResult Payment()
        {
            TempData["result"] = false;
            return View();
        }*/

        /*public IActionResult PaymentInvoice(int id)
        {
            return View(CustomerService.InvoiceTitle(new InvoiceTitleDto
            {
                id = id,
                userId = Convert.ToInt32(Request.Cookies["userId"])
            }));
        }*/

        /*[HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult PaymentInvoice(PaymentStartDto paymentStartDto)
        {
            if (!ModelState.IsValid)
                return View();

            paymentStartDto.path = HostingEnvironment.WebRootPath;
            paymentStartDto.userId = Convert.ToInt32(Request.Cookies["userId"]);
            paymentStartDto.pan = paymentStartDto.pan.Trim().Replace(" ", "");
            paymentStartDto.paymentType = PaymentTypeHelper.INVOICE;

            var controlModel = PaymentInitControl.control(paymentStartDto);
            if (controlModel.result)
            {
                paymentStartDto.pan = paymentStartDto.pan.Trim().Replace(" ", "");
                var result = PaymentStart.paymentStart(paymentStartDto);
                if (result.result)
                {
                    TempData["result"] = false;
                    byte[] bytes = Encoding.ASCII.GetBytes(result.message);
                    HttpContext.Response.Body.Write(bytes);
                }
                else
                {
                    TempData["result"] = true;
                    TempData["message"] = result.message;
                }
            }
            else
            {
                TempData["result"] = true;
                TempData["message"] = controlModel.message;
            }
            return RedirectToAction("PaymentInvoice", new { id = paymentStartDto.id });
        }*/

        /*[HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Payment(PaymentStartDto paymentStartDto)
        {
            if (!ModelState.IsValid)
                return View();

            paymentStartDto.userId = Convert.ToInt32(Request.Cookies["userId"]);
            paymentStartDto.paymentType = PaymentTypeHelper.BALANCE;
            paymentStartDto.path = HostingEnvironment.WebRootPath;
            var controlModel = PaymentInitControl.control(paymentStartDto);
            if (controlModel.result)
            {
                paymentStartDto.pan = paymentStartDto.pan.Trim().Replace(" ", "");
                paymentStartDto.documentNumber = "";
                var result = PaymentStart.paymentStart(paymentStartDto);
                if (result.result)
                {
                    TempData["result"] = false;
                    byte[] bytes = Encoding.ASCII.GetBytes(result.message);
                    HttpContext.Response.Body.Write(bytes);
                }
                else
                {
                    TempData["result"] = true;
                    TempData["message"] = result.message;
                }
            }
            else
            {
                TempData["result"] = true;
                TempData["message"] = controlModel.message;
            }
            return View();
        }*/
    }
}

SolvekEPayment/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="page-title">İletişim</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="/Home/Index">Ana Menü</a></li>
                    <li class="breadcrumb-item active">İletişim</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="card card-body">
            <h4 class="card-title" style="font-size:15px;">Uzmanlar Elk. Paz. San. ve Tic. Ltd. Şti.</h4>
            <p class="card-text">
                <strong>Adres</strong><br />
                Emekyemez Mahallesi - Okçumusa Caddesi - Şahlan Han No:34/A Beyoğlu/İstanbul
                <br /><br />

                <strong>Telefon</strong><br />
                0(212) 256 5200 - 0(212) 238 2233
                <br /><br />

                <strong>Fax</strong><br />
                0(212) 297 4687
                <br /><br />

                <strong>E-Posta</strong><br />
                info@uzmanlarelektrik.com.tr
                <br /><br />
            </p>
        </div>
    </div>
</div>

SolvekEPayment/Views/Home/Contract.cshtml
@{
    ViewData["Title"] = "Contract";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="page-title">Hizmet Sözleşmesi</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="/Home/Index">Ana Menü</a></li>
                    <li class="breadcrumb-item active">Hizmet Sözleşmesi</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="card card-body">
            <h4 class="card-title" style="font-size:15px;">Hizmet Sözleşmesi</h4>
            <p class="card-text">
                <strong>Kullanım Şartları</strong><br />
                http://odeme.uzmanlarelektrik.com.tr/ web sitesine hoş geldiniz.

                Bu web sitesinde sunulan hizmetlerin kullanım şartlarını, sitemize üye olarak veya hizmetlerimizden yararlanma aşamasında, bu sözleşmeyi kabul ettiğinizi beyan eden kutucuğu işaretleyerek kabul etmiş oluyorsunuz. http://odeme.uzmanlarelektrik.com.tr/ web sitesinde bulunan hizmetlerde kullanım özellik ve şartlarında önceden bir bildirimde bulunmaksızın, herhangi bir zamanda değişiklik
                yapma, yürürlükten kaldırma ve güncelleme haklarını saklı tutar.
                <br /><br />

                <strong>Garanti ve Feragat</strong><br />
                http://odeme.uzmanlarelektrik.com.tr/ ve sizin aranızda yapılan ayrı bir sözleşme ile açıkça belirlenmediği sürece, bu web sitesinden edinilen bütün hizmetler size olduğu haliyle sağlanmış olup, herhangi bir amaca uygunluk açısından veya başka bir açıdan herhangi bir garantiye tabi değildir.
                http://odeme.uzmanlarelektrik.com.tr/ hiçbir şekilde tarafınız veya başka bir üçüncü kişi tarafından bu web sitesine erişimden, bu web sitesinin veya bu web sitesinden linkle yönlendirilmiş başka bir web sitesine erişimden veya bu web sitesinde yer alan hizmetlerin kullanımı vasıtasıyla uğranılmış dolaysız veya dolaylı bir zarardan, gelir veya veri kaybından veya başka bir zarardan sorumlu değildir.
                <br /><br />
                Bu web sitesi üçüncü kişiler tarafından sağlanmış içerik veya yazılımlar bulunmaktadır. Bu web sitesinde yer alan bütün üçüncü kişilere ait içerik ve yazılımlar için de yukarıda yer alan “GARANTİ VE FERAGAT” bölümü hükümleri geçerlidir.
            </p>
        </div>
    </div>
</div>
<!-- end row -->

SolvekEPayment/Views/Home/FailUrl.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>FailUrl</title>
</head>
<body>
</body>
</html>

SolvekEPayment/Views/Home/Index.cshtml
@model SolvekEPayment.Models.ErpModels.CustomerBalanceTotalModelResponse
@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form action="/Home/Index" method="post">
    @*<form asp-controller="Payment" data-ajax-url="/PaymentRequset" data-ajax="true" method="post" data-ajax-mode="replace" data-ajax-begin="onBegin" data-ajax-failure="onFailure" data-ajax-success="onSuccess">
    *@

    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h4 class="page-title">Ana Menü</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="/Home/Index">Uzmanlar Online Tahsilat</a></li>
                        <li class="breadcrumb-item active">Ana Menü</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    @if (Convert.ToBoolean(TempData["result"]))
    {
        <div class="row">
            <div class="col-lg-12">
                <div class="card-box">
                    <div class="alert alert-danger fade show" role="alert">
                        @TempData["message"]
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {

    }
    @await Component.InvokeAsync("CustomerBalanceTotalComponent")

    <div class="row">
        <div class="col-lg-12">
            <div class="card-box">
                <div class="form-group">
                    <label class="col-xl-6 col-form-label">Ödenecek Tutar</label>
                    <div class="col-md-6">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1"><i class="mdi mdi-currency-try"></i></span>
                            </div>
                            <input type="text" class="form-control" placeholder="Tutar" aria-label="paymentTotal" id="paymentTotal" name="paymentTotal" aria-describedby="basic-addon1" maxlength="40">
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- end col -->
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="card-box">

                <h4 class="header-title mt-0 mb-3">Ödeme Bilgileri</h4>

                @Html.AntiForgeryToken()
                <div class="form-group">
                    <label class="col-xl-6 col-form-label">Kart Sahibi</label>
                    <div class="col-md-6">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1"><i class="mdi mdi-account-box"></i></span>
                            </div>
                            <input type="text" name="holder" class="form-control" placeholder="Kart üzerindeki ad soyad" aria-label="holder" aria-describedby="basic-addon1" maxlength="40" required>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-xl-6 col-form-label">Kart Numarası</label>
                    <div class="col-md-6">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1"><i class="mdi mdi-credit-card"></i></span>
                            </div>
                            <input type="text" name="pan" id="pan" class="form-control" placeholder="**** **** **** ****" aria-label="pan" aria-describedby="basic-addon1" maxlength="19" required>
                            <img src="~/content/images/mastercard.png" id="master" width="48" style="margin-left:5px; display: none;" />
                            <img src="~/content/images/visa.png" width="48" id="visa" style="margin-left:5px; display: none;" />
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-xl-6 col-form-label">Son Kullanma Tarihi</label>
                    <div class="col-md-6">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1"><i class="mdi mdi-calendar-blank"></i></span>
                            </div>
                            <input type="text" class="form-control" placeholder="MM/YY" aria-label="expire" name="expire" id="expire" aria-describedby="basic-addon1" maxlength="5" required>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-xl-6 col-form-label">Güvenlik Kodu</label>
                    <div class="col-md-6">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1"><i class="mdi mdi-shield-lock"></i></span>
                            </div>
                            <input type="text" class="form-control" placeholder="***" aria-label="cv" name="cv" id="cv" aria-describedby="basic-addon1" maxlength="3" required>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-xl-6 col-form-label">Banka Seçiniz</label>
                    <div class="col-md-6">
                        <select id="bankId" name="bankId" class="form-control">
                            <option value="-1">-- Seçiniz --</option>
                            <option value="1">Akbank</option>
                            <option value="2">Halkbank</option>
                            <option value="3">Teb Bankası</option>
                            <option value="4">İş Bankası</option>
                            <option value="5">Vakıfbank</option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-xl-6 col-form-label">Kartınızın Tipini Seçiniz</label>
                    <div class="col-md-6">
                        <select id="cardId" name="cardId" class="form-control">
                            <option value="-1">-- Seçiniz --</option>
                            <option value="1">Akbank - Axess</option>
                            <option value="2">Garanti - Bonus</option>
                            <option value="3">Finansbank - Cardfinans</option>
                            <option value="4">İşbank - Maximum</option>
                            <option value="5">Halbank - Paraf</option>
                            <option value="6">Vakıfbank - World</option>
                            <option value="7">Ziraat Bankası - Combo</option>
                            <option value="0">Diğer</option>
                        </select>
                    </div>
                </div>

                <div class="form-group" id="installmentMenu" >
                    <label class="col-xl-6 col-form-label">Taksit Seçiniz</label>
                    <div class="col-md-6">
                        <select id="installment" name="installment" class="form-control">
                            <option value="-1">-- Seçiniz --</option>
                            @await Component.InvokeAsync("InstallmentComponent")
                        </select>
                    </div>
                </div>

                <div class="form-group text-right mb-0">
                    <button class="btn btn-primary waves-effect waves-light mr-1" type="submit" id="btnPayment">
                        Ödemeyi Tamamla
                    </button>
                </div>
            </div>
        </div><!-- end col -->
    </div>
</form>

<div class="row">
    <div class="col-lg-12">
        <div class="card-box">
            <img src="~/content/images/footer-logo-visa.png" style="margin-right:10px;" />
            <img src="~/content/images/footer-logo-mastercard.png" style="margin-right:10px;" />
            <img src="~/content/images/ssl_logo.png" style="margin-right:10px;" />
            <img src="~/content/images/footer-logo-3d.png" style="margin-right:10px;" />
            <img src="~/content/images/troy.jpg" />
        </div>
    </div><!-- end col -->
</div>


@section Scripts{
    <script src="~/content/js/jquery.mask.js"></script>
    <script src="~/content/js/jquery.inputmask.bundle.min.js"></script>
    <script src="~/content/js/homeindex.js"></script>
}

SolvekEPayment/Views/Home/OkUrl.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>OkUrl</title>
    <link href="~/content/css/okurlstyle.css" rel="stylesheet" />
</head>
<body>
    <center style="margin-top: 15%;">
        <div class="loader">
        </div>
        <h3>Lütfen bekleyin..</h3>
    </center>
</body>
</html>

SolvekEPayment/Views/Home/PaymentComplete.cshtml
@model SolvekEPayment.Dtos.AppDtos.PaymentDto
@{
    ViewData["Title"] = "OkUrl";
}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Başarılı | Uzmanlar Online Tahsilat Sistemi</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
    <meta content="Coderthemes" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="assets/images/favicon.ico">

    <link href="~/content/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Bootstrap Css -->
    <!-- Icons Css -->
    <link href="~/content/css/icons.min.css" rel="stylesheet" />
    <!-- App Css-->
    <link href="~/content/css/app.min.css" rel="stylesheet" />

</head>


<body class="authentication-bg">

    <div class="account-pages mt-5 mb-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-6 col-xl-5">
                    <div class="text-center">
                        <a href="index.html" class="logo">
                            <img src="~/content/images/tick.png" alt="" height="128" class="logo-light mx-auto">
                            <img src="~/content/images/tick.png" alt="" height="128" class="logo-dark mx-auto">
                        </a>
                    </div>
                    <br />
                    <div class="card">

                        <div class="card-body p-4">

                            <div class="text-center">
                                <h2 class="mt-3 mb-2">İşlem Başarılı</h2>
                                @if (Model == null)
                                {
                                    <p class="text-muted mb-3">
                                        Ödeme başarı ile alındı.
                                    </p>

                                }
                                else
                                {
                                    <p class="text-muted mb-3">
                                        @Model.message
                                    </p>
                                }

                                <a href="/Home/Index" class="btn btn-danger waves-effect waves-light"><i class="fas fa-home mr-1"></i> Ana Sayfaya Dön</a>
                            </div>


                        </div> <!-- end card-body -->
                    </div>
                    <!-- end card -->

                </div> <!-- end col -->
            </div>
            <!-- end row -->
        </div>
        <!-- end container -->
    </div>
    <!-- end page -->
    <!-- Vendor js -->
    <script src="~/content/js/vendor.min.js"></script>
    <script src="~/content/js/app.min.js"></script>

</body>

</html>